name: Report via mdn/yari template
description: Used by mdn/yari — do not use this template
labels: ["via page report", "needs triage"]
body:
  - type: markdown
    attributes:
      value: |
        ### Want to edit this page?
        To edit this page directly, go back to the page and click the "Edit on GitHub" link.
        
        ### Before you start

        If your issue is about:

        - the **browser compatibility table** on this page, then go back to the page and use the _Report problems with this compatibility data on GitHub_ link instead.
        - **getting help with Firefox, Chrome, Safari, or another browser**, then check the browser's support site instead. <!-- TODO: link to Firefox, Chrome, Safari help sites -->

        ---
  - type: input
    id: section
    attributes:
      label: What specific section or headline is this issue about?
