name: Report via mdn/yari template
description: Used by mdn/yari — do not use this template
labels: ["via page report", "needs triage"]
body:
  - type: markdown
    attributes:
      value: |
        ### Want to edit this page?
        To edit this page directly, go back to the page and click the "Edit on GitHub" link.
        
        ### Before you continue

        If this is about a **browser compatibility table**, go back to the page and use the _Report problems with this compatibility data on GitHub_ link instead.

        If this is about **a browser bug or feature request**, do not use this form. Check the browser's support site instead. <!-- TODO: link to Firefox, Chrome, Safari help sites -->
  - type: input
    attributes:
      label: test
      description: test
      placeholder: test