name: Report via mdn/yari template
description: Used by mdn/yari — do not use this template
labels: ["via page report", "needs triage"]
body:
  - type: markdown
    attributes:
      value: |
        ### Want to edit this page?
        To edit this page directly, go back to the page and click the "Edit on GitHub" link.
        
        ### Before you start

        If your issue is about:

        - the **browser compatibility table** on this page, then go back to the page and use the _Report problems with this compatibility data on GitHub_ link instead.
        - **getting help with Firefox, Chrome, Safari, or another browser**, then check the browser's support site instead. <!-- TODO: link to Firefox, Chrome, Safari help sites -->

        ---
  - type: input
    id: section
    attributes:
      label: What specific section or headline is this issue about?
  - type: textarea
    id: problem
    attributes:
      label: What information was incorrect, unhelpful, or incomplete?
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: What did you expect to see?
    validations:
      required: true
  - type: textarea
    id: references
    attributes:
      label: Do you have any supporting links, references, or citations?
      description: Link to information that helps us confirm your issue.
  - type: textarea
    id: more-info
    attributes:
      label: Do you have anything more you want to share?
      description: For example, steps to reproduce a bug, screenshots, screen recordings, or sample code
  - type: markdown
    attributes:
      value: |
        ---
        You're finished! The following fields are prefilled. Please click **Submit new issue**.
  - type: input
    id: metadata-url
    attributes:
      label: MDN URL
      description: Added automatically. Do not modify.
    validations:
      required: true